language: rust
cache: cargo
os:
  - windows
  - osx
  - linux
rust:
  # - stable
  - beta
  - nightly
branches:
  only:
    - master
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --check
  - cargo test
