language: rust
cache: cargo
rust:
- stable
- beta
- nightly
branches:
  only:
  - master
matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
before_script:
- rustup component add rustfmt-preview

script:
- cargo fmt --all -- --check
- cargo test
