[package]
name = "lightning"
version = "0.1.0"
authors = ["Chris Krycho <chris@chriskrycho.com>"]

[[bin]]
name = "lx"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
chrono-tz = "0.4"
glob = "0.2.11"
pandoc = "0.5.2"
quick-xml = "0.4.1"
syntect = "1.0.1"  # TODO: make this a feature dependency
yaml-rust = "0.3.5"

[dependencies.clap]
version = "~2.19.0"
features = [ "yaml" ]

[profile.release]
# debug = true  # For profiling only.
