[package]
name = "lightning"
version = "0.1.0"
authors = ["Chris Krycho <hello@chriskrycho.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
glob = "0.2.11"
quick-xml = "0.4.1"
pulldown-cmark = { version = "0.0.11", default-features = false }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
syntect = "3.0"
structopt = "0.2.13"
yaml-rust = "0.3.5"

[profile.release]
# debug = true  # For profiling only.
