[package]
name = "lightning"
version = "0.1.0"
authors = ["Chris Krycho <chris@chriskrycho.com>"]

[[bin]]
name = "lx"

[dependencies]
glob = "0.2.11"
syntect = "1.0.1"
pandoc = { git = "https://github.com/chriskrycho/rust-pandoc", branch = "builder" }
quick-xml = "0.4.1"

[dependencies.clap]
version = "~2.19.0"
features = [ "yaml" ]

[profile.release]
# debug = true  # For profiling only.
