[package]
name = "lightning"
version = "0.1.0"
authors = ["Chris Krycho <chris@chriskrycho.com>"]

[dependencies]
clap = "2.15.0"
glob = "0.2.11"
syntect = "1.0.1"
pandoc = { git = "https://github.com/chriskrycho/rust-pandoc", branch = "builder" }
quick-xml = "0.4.1"

[[bin]]
name = "lng"  # TODO: maybe?

[profile.release]
# debug = true  # For profiling only.
