[package]
name = "lightning"
version = "0.1.0"
authors = ["Chris Krycho <chris@chriskrycho.com>"]
edition = "2018"

[dependencies]
glob = "0.2.11"
pandoc = "0.7.0"
quick-xml = "0.13.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
syntect = "3.0.1"
yaml-rust = "0.4.2"

[dependencies.clap]
version = "2.32.0"
features = [ "yaml" ]

[profile.release]
# debug = true  # For profiling only.
