module.exports = [
   { type: 'page', title: 'Archive', path: '/archive/' },
   { type: 'separator' },
   // { type: 'page', title: 'Essays', path: '/essays/' },
   { type: 'page', title: 'Journal', path: '/journal/' },
   { type: 'page', title: 'Library', path: '/library/' },
   { type: 'page', title: 'Notes', path: '/notes/' },
   // { type: 'page', title: 'Longform', path: '#' },
   // { type: 'separator' },
   // { type: 'page', title: 'Photos', path: '#' },
   { type: 'page', title: 'Elsewhere', path: '/elsewhere/' },
   { type: 'separator' },
   //   { type: 'page', title: 'Projects', path: '/projects/' },
   { type: 'page', title: 'About', path: '/about/' },
   { type: 'page', title: 'Curriculum Vitae', path: '/cv/' },
   { type: 'separator' },
   { type: 'page', title: 'Colophon', path: '/colophon/' },
]
